[package]
name = "obsbot-center"
description = "Linux configuration tool for OBSBOT webcams"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "obsbot_center_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
obsbot-core.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2", features = [] }
