[package]
name = "obscura"
description = "OBSCura: unofficial control panel for OBSBOT webcams"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "obscura_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
obsbot-core = { workspace = true, features = ["update-check"] }
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2", features = [] }
